# Generated by Django 4.1.3 on 2023-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_nb',
            field=models.IntegerField(default='0'),
        ),
    ]
