# Generated by Django 4.1.3 on 2023-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_noti_nb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='noti_nb',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='/'),
        ),
    ]
