# Generated by Django 4.1.3 on 2022-11-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='fk_project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='fk_user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
