# Generated by Django 4.1.3 on 2022-12-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
