# Generated by Django 4.1.3 on 2022-12-05 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('www', '0004_remove_userproject_project_remove_userproject_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=45)),
                ('description', models.TextField(default='/', max_length=512)),
                ('progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(related_name='collaborator_project_set', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_project_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
