# Generated by Django 4.1.3 on 2022-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_alter_project_collaborators_alter_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='is_manager',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
