# Generated by Django 4.1.3 on 2022-12-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_remove_project_collaborators_remove_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='final',
            new_name='is_final',
        ),
    ]
