# Generated by Django 4.1.3 on 2022-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0013_rename_final_status_is_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='designation',
            field=models.CharField(default='Statut', max_length=45),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
