# Generated by Django 4.1.3 on 2022-12-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0014_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_time_created',
            new_name='datetime_created',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Tâche', max_length=45)),
                ('subtask_id', models.IntegerField(default=0)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration', to='www.collaboration')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='www.status')),
            ],
        ),
    ]
