# Generated by Django 4.1.3 on 2022-12-25 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0016_remove_task_collaboration_task_project_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.UUIDField(default=uuid.UUID('50c27431-06c8-4b4b-886e-473e6f1d3288'), editable=False),
        ),
    ]
