# Generated by Django 4.1.3 on 2022-12-25 15:27

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('www', '0017_invitation_is_active_alter_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fecbbe51-dc7f-4eb0-bbb6-3c60797bbaae'), editable=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='i_receivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
