# Generated by Django 4.1.3 on 2023-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0022_log_user_alter_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='962a2dc9bd530097', max_length=16),
        ),
    ]
