# Generated by Django 4.1.3 on 2023-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0024_alter_invitation_key_changestatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='1b93b61a44ee9e4e', max_length=16),
        ),
    ]
