# Generated by Django 4.1.3 on 2023-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0027_status_color_alter_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='4b4d4d917bf711d0', max_length=16),
        ),
    ]
