# Generated by Django 4.1.3 on 2023-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0031_alter_invitation_key_taskstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='a268239ff4b75403', max_length=16),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='datetime_stop',
            field=models.DateTimeField(default=None),
        ),
    ]
