# Generated by Django 4.1.3 on 2023-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0032_alter_invitation_key_alter_taskstate_datetime_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='14e9c6b8bd5a0b2f', max_length=16),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='datetime_stop',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
