# Generated by Django 4.1.3 on 2023-01-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0033_alter_invitation_key_alter_taskstate_datetime_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='18ca9e153005d5f9', max_length=16),
        ),
    ]
