# Generated by Django 4.1.3 on 2023-01-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0034_alter_invitation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progression',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='5b968dc1b55bd2ec', max_length=16),
        ),
    ]
