# Generated by Django 4.1.3 on 2023-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0036_log_alter_invitation_key_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.CharField(default='123d14db444ccd4b', max_length=16),
        ),
    ]
